# -*- coding: utf-8 -*-
"""Dashboard_Streamlit_9(new 2hr ahead data).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x52wyaDF12S1TI87se78_g88hpuhA61g
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from datetime import time
from textwrap import dedent

st.set_page_config(
    page_title="Solar GHI Forecasting Dashboard",
    layout="wide"
)

st.markdown(
    "<h1 style='text-align: center;'>☀️ Solar GHI Forecasting Dashboard</h1>",
    unsafe_allow_html=True
)

DATA_PATH = "Bias Correction_with_Day_Ahead_2hrahead_Forecast_3.csv"

@st.cache_data
def load_data():
    df = pd.read_csv(DATA_PATH)

    df["valid_time_ist"] = (
        pd.to_datetime(df["valid_time_ist"])
          .dt.tz_localize(None)
    )
    df["valid_time_ist"] = pd.to_datetime(df["valid_time_ist"])

    df = df.rename(columns={
        "avg_ghi": "GFS_GHI",
        "ALLSKY_SFC_SW_DWN": "Actual_GHI",
        "Day_Ahead_Forecast": "Daily_Forecast_GHI",
        "2hr_ahead_forecast": "Two_Hour_Ahead_Forecast"
    })

    df = df.sort_values("valid_time_ist").reset_index(drop=True)
    return df

df = load_data()

# =====================================================
# CACHED MONTH-WISE MAE — DAILY FORECAST
# One bar per calendar month across all years
# =====================================================

@st.cache_data
def calculate_monthly_daily_mae(input_df):

    monthly_df = input_df.dropna(
        subset=[
            "valid_time_ist",
            "Actual_GHI",
            "Daily_Forecast_GHI"
        ]
    ).copy()

    monthly_df["hour"] = (
        monthly_df["valid_time_ist"].dt.hour
        + monthly_df["valid_time_ist"].dt.minute / 60
    )

    monthly_df = monthly_df[
        (monthly_df["hour"] >= 6.5)
        & (monthly_df["hour"] <= 17.5)
        & (monthly_df["Actual_GHI"] > 50)
    ].copy()

    if monthly_df.empty:
        return pd.DataFrame(), None, None

    monthly_df["Absolute_Error"] = (
        monthly_df["Actual_GHI"]
        - monthly_df["Daily_Forecast_GHI"]
    ).abs()

    monthly_df["Month_Number"] = (
        monthly_df["valid_time_ist"].dt.month
    )

    monthly_result = (
        monthly_df
        .groupby("Month_Number", as_index=False)
        .agg(Monthly_MAE=("Absolute_Error", "mean"))
        .sort_values("Month_Number")
        .reset_index(drop=True)
    )

    month_names = {
        1: "Jan",
        2: "Feb",
        3: "Mar",
        4: "Apr",
        5: "May",
        6: "Jun",
        7: "Jul",
        8: "Aug",
        9: "Sep",
        10: "Oct",
        11: "Nov",
        12: "Dec"
    }

    monthly_result["Month"] = (
        monthly_result["Month_Number"].map(month_names)
    )

    start_date = monthly_df["valid_time_ist"].dt.date.min()
    end_date = monthly_df["valid_time_ist"].dt.date.max()

    return monthly_result, start_date, end_date

# =====================================================
# CACHED MONTH-WISE MAE — 2-HOUR AHEAD FORECAST
# One bar per calendar month across all years
# =====================================================

@st.cache_data
def calculate_monthly_2hr_mae(input_df):

    monthly_df = input_df.dropna(
        subset=[
            "valid_time_ist",
            "Actual_GHI",
            "Two_Hour_Ahead_Forecast"
        ]
    ).copy()

    monthly_df["hour"] = (
        monthly_df["valid_time_ist"].dt.hour
        + monthly_df["valid_time_ist"].dt.minute / 60
    )

    monthly_df = monthly_df[
        (monthly_df["hour"] >= 6.5)
        & (monthly_df["hour"] <= 17.5)
        & (monthly_df["Actual_GHI"] > 50)
    ].copy()

    if monthly_df.empty:
        return pd.DataFrame(), None, None

    monthly_df["Absolute_Error"] = (
        monthly_df["Actual_GHI"]
        - monthly_df["Two_Hour_Ahead_Forecast"]
    ).abs()

    monthly_df["Month_Number"] = (
        monthly_df["valid_time_ist"].dt.month
    )

    monthly_result = (
        monthly_df
        .groupby("Month_Number", as_index=False)
        .agg(Monthly_MAE=("Absolute_Error", "mean"))
        .sort_values("Month_Number")
        .reset_index(drop=True)
    )

    month_names = {
        1: "Jan",
        2: "Feb",
        3: "Mar",
        4: "Apr",
        5: "May",
        6: "Jun",
        7: "Jul",
        8: "Aug",
        9: "Sep",
        10: "Oct",
        11: "Nov",
        12: "Dec"
    }

    monthly_result["Month"] = (
        monthly_result["Month_Number"].map(month_names)
    )

    start_date = monthly_df["valid_time_ist"].dt.date.min()
    end_date = monthly_df["valid_time_ist"].dt.date.max()

    return monthly_result, start_date, end_date

st.subheader("🏭 Plant & Forecast Configuration")

available_dates = sorted(df["valid_time_ist"].dt.date.unique())

c1, c2, c3, c4 = st.columns([1, 1.5, 1, 1])

with c1:
    state = st.selectbox(
        "State",
        ["Karnataka"]
    )

with c2:
    plant = st.selectbox(
        "Plant Name",
        ["Pavagada Solar Plant"]
    )

with c3:
    selected_date = st.date_input(
        "Date",
        value=available_dates[-1],
        min_value=available_dates[0],
        max_value=available_dates[-1]
    )

with c4:
    time_options = pd.date_range("06:30", "17:30", freq="1h").time

    selected_time = st.selectbox(
        "Time",
        options=time_options,
        format_func=lambda t: t.strftime("%H:%M")
    )


day_df = df[df["valid_time_ist"].dt.date == selected_date].copy()

day_df["hour"] = (
    day_df["valid_time_ist"].dt.hour +
    day_df["valid_time_ist"].dt.minute / 60
)

day_df = day_df[
    (day_df["hour"] >= 6.5) &
    (day_df["hour"] <= 17.5)
].copy()

selected_datetime = pd.to_datetime(
    str(selected_date) + " " + selected_time.strftime("%H:%M")
)

two_hour_end_time = selected_datetime + pd.Timedelta(hours=2)

target_row = day_df[
    day_df["valid_time_ist"] == two_hour_end_time
]

has_two_hour_forecast = (
    not target_row.empty and
    pd.notna(target_row["Two_Hour_Ahead_Forecast"].iloc[0])
)

if has_two_hour_forecast:
    two_hour_df = day_df[
        day_df["valid_time_ist"] <= two_hour_end_time
    ].copy()

    two_hour_df = two_hour_df.dropna(
        subset=["Two_Hour_Ahead_Forecast"]
    )
else:
    two_hour_df = pd.DataFrame()


if day_df.empty:
    st.stop()

else:

    left_col, right_col = st.columns(2)

    ymax = max(
        day_df["Actual_GHI"].max(),
        day_df["GFS_GHI"].max(),
        day_df["Daily_Forecast_GHI"].max()
    )

    ymax = (int(ymax / 100) + 1) * 100

    tick_times = day_df["valid_time_ist"].dt.strftime("%H:%M").tolist()

    # ============================
    # Dashboard Colors
    # ============================
    GFS_COLOR = "#76B7F2"             # Light blue
    DAILY_FORECAST_COLOR = "#F28E2B"  # Orange
    DAILY_FORECAST_FILL = "rgba(242,142,43,0.25)"
    TWO_HOUR_COLOR = "#2CA02C"        # Green
    ACTUAL_COLOR = "#636EFA"          # Blue

    # =====================================================
    # FIRST ROW: DAILY FORECAST GHI ONLY
    # =====================================================

    fig1 = go.Figure()

    fig1.add_trace(go.Scatter(
        x=day_df["valid_time_ist"],
        y=day_df["Daily_Forecast_GHI"],
        mode="lines+markers",
        name="Daily Forecast GHI",
        line=dict(color=DAILY_FORECAST_COLOR, width=2),
        marker=dict(color=DAILY_FORECAST_COLOR),
         fill="tozeroy",
        fillcolor=DAILY_FORECAST_FILL
    ))

    if has_two_hour_forecast:

        fig1.add_trace(go.Scatter(
            x=two_hour_df["valid_time_ist"],
            y=two_hour_df["Two_Hour_Ahead_Forecast"],
            mode="lines+markers",
            name="2-Hour Ahead Forecast",
            line=dict(color=TWO_HOUR_COLOR),
            marker=dict(color=TWO_HOUR_COLOR)
        ))

    else:
        pass

    fig1.update_layout(
        title=dict(
            text=f"Forecasted GHI for {selected_date}",
            font=dict(size=24)
        ),
        xaxis_title="Time",
        yaxis_title="GHI",
        height=450,
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1
        )
    )

    fig1.update_xaxes(
        tickmode="array",
        tickvals=day_df["valid_time_ist"],
        ticktext=tick_times
    )

    fig1.update_yaxes(range=[0, ymax])

    row1_col, row1_space = st.columns([4.5, 0.8])

    with row1_col:
        st.plotly_chart(fig1, use_container_width=True, key="daily_forecast_main")

    with row1_space:

        with st.container(border=True):

            st.markdown("### 📥 Export Forecast Data")

            download_cols = [
                "valid_time_ist",
                "Actual_GHI",
                "GFS_GHI",
                "Daily_Forecast_GHI",
                "Two_Hour_Ahead_Forecast"
            ]

            rename_download_cols = {
                "valid_time_ist": "Time",
                "Actual_GHI": "Actual GHI",
                "GFS_GHI": "GFS GHI",
                "Daily_Forecast_GHI": "Day Ahead Forecast GHI",
                "Two_Hour_Ahead_Forecast": "2-Hour Ahead Forecast GHI"
            }

            # =====================================================
            # DOWNLOAD 1: START OF DATA TO SELECTED DATE
            # =====================================================

            cumulative_download_df = df[
                df["valid_time_ist"].dt.date <= selected_date
            ].copy()

            cumulative_download_df["hour"] = (
                cumulative_download_df["valid_time_ist"].dt.hour
                + cumulative_download_df["valid_time_ist"].dt.minute / 60
            )

            cumulative_download_df = cumulative_download_df[
                (cumulative_download_df["hour"] >= 6.5)
                & (cumulative_download_df["hour"] <= 17.5)
            ].copy()

            cumulative_download_df = cumulative_download_df[
                download_cols
            ].rename(columns=rename_download_cols)

            cumulative_csv = cumulative_download_df.to_csv(
                index=False
            ).encode("utf-8")


            st.download_button(
                label="⬇️ Download data through selected date",
                data=cumulative_csv,
                file_name=f"forecast_data_through_{selected_date}.csv",
                mime="text/csv",
                use_container_width=True,
                key="download_cumulative_forecast"
            )


            # =====================================================
            # DOWNLOAD 2: SELECTED DATE ONLY
            # =====================================================

            day_download_df = day_df[
                download_cols
            ].copy().rename(columns=rename_download_cols)

            day_csv = day_download_df.to_csv(
                index=False
            ).encode("utf-8")

            st.download_button(
                label="⬇️ Download selected day data",
                data=day_csv,
                file_name=f"forecast_data_{selected_date}.csv",
                mime="text/csv",
                use_container_width=True,
                key="download_selected_day_forecast"
            )

    # =====================================================
    # SECOND ROW: TWO PLOTS
    # LEFT: GFS VS DAILY FORECAST
    # RIGHT: DAILY FORECAST GHI ONLY
    # =====================================================

    left_col, right_col = st.columns(2)

    left_col, right_col = st.columns(2)

    with left_col:

        with st.container(border=True):

            st.markdown("### GFS vs Daily Forecast GHI")

            fig2 = go.Figure()

            fig2.add_trace(go.Scatter(
                x=day_df["valid_time_ist"],
                y=day_df["GFS_GHI"],
                mode="lines+markers",
                name="GFS GHI",
                line=dict(color=GFS_COLOR),
                marker=dict(color=GFS_COLOR)
            ))

            fig2.add_trace(go.Scatter(
                x=day_df["valid_time_ist"],
                y=day_df["Daily_Forecast_GHI"],
                mode="lines+markers",
                name="Daily Forecast GHI",
                line=dict(color=DAILY_FORECAST_COLOR),
                marker=dict(color=DAILY_FORECAST_COLOR)

            ))

            fig2.update_layout(
                xaxis_title="Time",
                yaxis_title="GHI",
                height=430,
                margin=dict(l=20, r=20, t=45, b=20),
                legend=dict(
                    orientation="h",
                    yanchor="bottom",
                    y=1.02,
                    xanchor="right",
                    x=1
                )
            )

            fig2.update_xaxes(
                tickmode="array",
                tickvals=day_df["valid_time_ist"],
                ticktext=tick_times
            )

            fig2.update_yaxes(range=[0, ymax])

            st.plotly_chart(
                fig2,
                use_container_width=True,
                key="gfs_vs_daily_forecast"
            )


    with right_col:
        with st.container(border=True):
            st.markdown("### GFS vs 2-Hour Ahead Forecast")

            fig3 = go.Figure()

            if has_two_hour_forecast:
                fig3.add_trace(go.Scatter(
                    x=two_hour_df["valid_time_ist"],
                    y=two_hour_df["GFS_GHI"],
                    mode="lines+markers",
                    name="GFS GHI",
                    line=dict(color=GFS_COLOR),
                    marker=dict(color=GFS_COLOR)
                ))

                fig3.add_trace(go.Scatter(
                    x=two_hour_df["valid_time_ist"],
                    y=two_hour_df["Two_Hour_Ahead_Forecast"],
                    mode="lines+markers",
                    name="2-Hour Ahead Forecast",
                    line=dict(color=TWO_HOUR_COLOR),
                    marker=dict(color=TWO_HOUR_COLOR)
                ))

                fig3_tick_vals = two_hour_df["valid_time_ist"]
                fig3_tick_times = (
                    two_hour_df["valid_time_ist"]
                    .dt.strftime("%H:%M")
                    .tolist()
                )

            else:
                selected_target_time = two_hour_end_time.strftime("%H:%M")

                st.warning(
                    f"No 2-hour ahead forecast available on {selected_date} "
                    f"for selected time {selected_time.strftime('%H:%M')} "
                    f"(target time: {selected_target_time})"
                )

                fig3_tick_vals = day_df["valid_time_ist"]
                fig3_tick_times = (
                    day_df["valid_time_ist"]
                    .dt.strftime("%H:%M")
                    .tolist()
                )

            fig3.update_layout(
                xaxis_title="Time",
                yaxis_title="GHI",
                height=430,
                margin=dict(l=20, r=20, t=45, b=20),
                legend=dict(
                    orientation="h",
                    yanchor="bottom",
                    y=1.02,
                    xanchor="right",
                    x=1
                )
            )

            fig3.update_xaxes(
                tickmode="array",
                tickvals=fig3_tick_vals,
                ticktext=fig3_tick_times
            )

            fig3.update_yaxes(range=[0, ymax])

            st.plotly_chart(
                fig3,
                use_container_width=True,
                key="two_hour_gfs_comparison"
            )

    # =====================================================
    # PREVIOUS DAY COMPARISON PLOTS
    # =====================================================

    selected_date_only = pd.to_datetime(selected_date).date()
    previous_day = selected_date_only - pd.Timedelta(days=1)

    previous_df = df[
        df["valid_time_ist"].dt.date == previous_day
    ].copy()

    previous_df["hour"] = (
        previous_df["valid_time_ist"].dt.hour
        + previous_df["valid_time_ist"].dt.minute / 60
    )

    previous_df = previous_df[
        (previous_df["hour"] >= 6.5)
        & (previous_df["hour"] <= 17.5)
    ].copy()

    if previous_df.empty:
        st.warning(
            f"No previous-day data available for {previous_day}."
        )

    else:
        st.markdown(
            f"""
            <h2 style="margin-top:20px; margin-bottom:10px;">
                📈 Previous Day Performance Comparison ({previous_day})
            </h2>
            """,
            unsafe_allow_html=True
        )

        # Common y-axis maximum
        prev_ymax = max(
            previous_df["Actual_GHI"].max(),
            previous_df["GFS_GHI"].max(),
            previous_df["Daily_Forecast_GHI"].max(),
            previous_df["Two_Hour_Ahead_Forecast"].max(skipna=True)
        )

        prev_ymax = (int(prev_ymax / 100) + 1) * 100

        prev_tick_times = (
            previous_df["valid_time_ist"]
            .dt.strftime("%H:%M")
            .tolist()
        )

        prev_left, prev_right = st.columns(2)

        # =====================================================
        # PREVIOUS DAY LEFT PLOT
        # Actual + GFS + Daily Forecast
        # =====================================================

        with prev_left:
            with st.container(border=True):

                st.markdown(
                    "### Actual vs GFS vs Daily Forecast"
                )

                fig_prev1 = go.Figure()

                # Actual GHI — green dotted
                fig_prev1.add_trace(go.Scatter(
                    x=previous_df["valid_time_ist"],
                    y=previous_df["Actual_GHI"],
                    mode="lines+markers",
                    name="Actual GHI",
                    line=dict(color=ACTUAL_COLOR, dash="dot"),
                    marker=dict(color=ACTUAL_COLOR)
                ))

                # GFS GHI — blue
                fig_prev1.add_trace(go.Scatter(
                    x=previous_df["valid_time_ist"],
                    y=previous_df["GFS_GHI"],
                    mode="lines+markers",
                    name="GFS GHI",
                    line=dict(color=GFS_COLOR),
                    marker=dict(color=GFS_COLOR)
                ))

                # Daily Forecast — orange
                fig_prev1.add_trace(go.Scatter(
                    x=previous_df["valid_time_ist"],
                    y=previous_df["Daily_Forecast_GHI"],
                    mode="lines+markers",
                    name="Daily Forecast GHI",
                    line=dict(color=DAILY_FORECAST_COLOR),
                    marker=dict(color=DAILY_FORECAST_COLOR)
                ))

                fig_prev1.update_layout(
                    xaxis_title="Time",
                    yaxis_title="GHI",
                    height=430,
                    margin=dict(
                        l=20,
                        r=20,
                        t=45,
                        b=20
                    ),
                    legend=dict(
                        orientation="h",
                        yanchor="bottom",
                        y=1.02,
                        xanchor="right",
                        x=1
                    )
                )

                fig_prev1.update_xaxes(
                    tickmode="array",
                    tickvals=previous_df["valid_time_ist"],
                    ticktext=prev_tick_times
                )

                fig_prev1.update_yaxes(
                    range=[0, prev_ymax]
                )

                st.plotly_chart(
                    fig_prev1,
                    use_container_width=True,
                    key="previous_day_actual_gfs_forecast"
                )

        # =====================================================
        # PREVIOUS DAY RIGHT PLOT
        # Actual + GFS + 2-Hour Ahead
        # =====================================================

        with prev_right:
            with st.container(border=True):

                st.markdown(
                    "### Actual vs GFS vs 2-Hour Ahead Forecast"
                )

                fig_prev2 = go.Figure()

                # Since the previous day is complete, use all rows
                # where 2-hour-ahead forecast exists.
                previous_two_hour_df = previous_df.dropna(
                    subset=["Two_Hour_Ahead_Forecast"]
                ).copy()

                if not previous_two_hour_df.empty:

                    # Actual GHI — green dotted
                    fig_prev2.add_trace(go.Scatter(
                        x=previous_two_hour_df["valid_time_ist"],
                        y=previous_two_hour_df["Actual_GHI"],
                        mode="lines+markers",
                        name="Actual GHI",
                        line=dict(color=ACTUAL_COLOR, dash="dot"),
                        marker=dict(color=ACTUAL_COLOR)
                    ))

                    # GFS GHI — blue
                    fig_prev2.add_trace(go.Scatter(
                        x=previous_two_hour_df["valid_time_ist"],
                        y=previous_two_hour_df["GFS_GHI"],
                        mode="lines+markers",
                        name="GFS GHI",
                        line=dict(color=GFS_COLOR),
                        marker=dict(color=GFS_COLOR)
                    ))

                    # 2-Hour Ahead Forecast — red
                    fig_prev2.add_trace(go.Scatter(
                        x=previous_two_hour_df["valid_time_ist"],
                        y=previous_two_hour_df[
                            "Two_Hour_Ahead_Forecast"
                        ],
                        mode="lines+markers",
                        name="2-Hour Ahead Forecast",
                        line=dict(color=TWO_HOUR_COLOR),
                        marker=dict(color=TWO_HOUR_COLOR)

                    ))

                    prev2_tick_vals = (
                        previous_two_hour_df["valid_time_ist"]
                    )

                    prev2_tick_text = (
                        previous_two_hour_df["valid_time_ist"]
                        .dt.strftime("%H:%M")
                        .tolist()
                    )

                else:
                    st.warning(
                        f"No previous-day 2-hour ahead forecast "
                        f"data available for {previous_day}."
                    )

                    prev2_tick_vals = previous_df["valid_time_ist"]

                    prev2_tick_text = (
                        previous_df["valid_time_ist"]
                        .dt.strftime("%H:%M")
                        .tolist()
                    )

                fig_prev2.update_layout(
                    xaxis_title="Time",
                    yaxis_title="GHI",
                    height=430,
                    margin=dict(
                        l=20,
                        r=20,
                        t=45,
                        b=20
                    ),
                    legend=dict(
                        orientation="h",
                        yanchor="bottom",
                        y=1.02,
                        xanchor="right",
                        x=1
                    )
                )

                fig_prev2.update_xaxes(
                    tickmode="array",
                    tickvals=prev2_tick_vals,
                    ticktext=prev2_tick_text
                )

                fig_prev2.update_yaxes(
                    range=[0, prev_ymax]
                )

                st.plotly_chart(
                    fig_prev2,
                    use_container_width=True,
                    key="previous_day_two_hour_actual_gfs"
                )


    st.info(
    "📌 Evaluation Criteria:  All forecast performance metrics are "
    "computed with "
    "Actual GHI > 50 W/m². Periods with lower irradiance are excluded "
    "from evaluation to ensure meaningful assessment."
)

    # =====================================================
    # CUMULATIVE ERROR METRICS: START DATE TO PREVIOUS DAY
    # =====================================================

    selected_date_only = pd.to_datetime(selected_date).date()
    previous_day = selected_date_only - pd.Timedelta(days=1)

    eval_df = df[
        df["valid_time_ist"].dt.date <= previous_day
    ].copy()

    eval_df = eval_df.dropna(
        subset=["Actual_GHI", "GFS_GHI", "Daily_Forecast_GHI"]
    )

    eval_df["hour"] = (
        eval_df["valid_time_ist"].dt.hour +
        eval_df["valid_time_ist"].dt.minute / 60
    )

    eval_df = eval_df[
        (eval_df["hour"] >= 6.5) &
        (eval_df["hour"] <= 17.5) &
        (eval_df["Actual_GHI"] > 50)
    ].copy()

    if not eval_df.empty:

        start_date = eval_df["valid_time_ist"].dt.date.min()
        end_date = eval_df["valid_time_ist"].dt.date.max()

        actual = eval_df["Actual_GHI"]
        before = eval_df["GFS_GHI"]
        after = eval_df["Daily_Forecast_GHI"]

        mae_before = (actual - before).abs().mean()
        mae_after = (actual - after).abs().mean()

        rmse_before = np.sqrt(((actual - before) ** 2).mean())
        rmse_after = np.sqrt(((actual - after) ** 2).mean())

        mape_before = ((actual - before).abs() / actual).mean() * 100
        mape_after = ((actual - after).abs() / actual).mean() * 100

        st.markdown(
            f"### 📊 Cumulative Performance of  Daily Forecast "
            f"({start_date} to {end_date})"
        )

        metric_col1, metric_col2, metric_col3 = st.columns(3)

        # ---------------- MAPE ----------------
        with metric_col1:
            fig_mape = go.Figure()

            fig_mape.add_trace(go.Bar(
                x=["Raw GFS Prediction", "After Daily Forecast"],
                y=[mape_before, mape_after],
                text=[round(mape_before, 2), round(mape_after, 2)],
                textposition="auto",
                marker_color=[GFS_COLOR, DAILY_FORECAST_COLOR]
            ))

            fig_mape.update_layout(
                title="MAPE",
                xaxis_title="Forecast Stage",
                yaxis_title="MAPE (%)",
                height=350
            )

            st.plotly_chart(
                fig_mape,
                use_container_width=True,
                key="mape_cumulative_chart"
            )

        # ---------------- MAE ----------------
        with metric_col2:
            fig_mae = go.Figure()

            fig_mae.add_trace(go.Bar(
                x=["Raw GFS Prediction", "After Daily Forecast"],
                y=[mae_before, mae_after],
                text=[round(mae_before, 2), round(mae_after, 2)],
                textposition="auto",
                marker_color=[GFS_COLOR, DAILY_FORECAST_COLOR]
            ))

            fig_mae.update_layout(
                title="MAE",
                xaxis_title="Forecast Stage",
                yaxis_title="MAE",
                height=350
            )

            st.plotly_chart(
                fig_mae,
                use_container_width=True,
                key="mae_cumulative_chart"
            )

        # ---------------- RMSE ----------------
        with metric_col3:
            fig_rmse = go.Figure()

            fig_rmse.add_trace(go.Bar(
                x=["Raw GFS Prediction", "After Daily Forecast"],
                y=[rmse_before, rmse_after],
                text=[round(rmse_before, 2), round(rmse_after, 2)],
                textposition="auto",
                marker_color=[GFS_COLOR, DAILY_FORECAST_COLOR]
            ))

            fig_rmse.update_layout(
                title="RMSE",
                xaxis_title="Forecast Stage",
                yaxis_title="RMSE",
                height=350
            )

            st.plotly_chart(
                fig_rmse,
                use_container_width=True,
                key="rmse_cumulative_chart"
            )

    else:
        st.warning(
            "Not enough valid previous-day data to calculate cumulative forecast performance."
        )

    # =====================================================
    # CUMULATIVE 2-HOUR-AHEAD FORECAST PERFORMANCE
    # Start of data through previous day
    # =====================================================

    cumulative_2hr_df = df[
        df["valid_time_ist"].dt.date <= previous_day
    ].copy()

    cumulative_2hr_df["hour"] = (
        cumulative_2hr_df["valid_time_ist"].dt.hour
        + cumulative_2hr_df["valid_time_ist"].dt.minute / 60
    )

    # Use only rows where all required values are available
    cumulative_2hr_df = cumulative_2hr_df.dropna(
        subset=[
            "Actual_GHI",
            "GFS_GHI",
            "Daily_Forecast_GHI",
            "Two_Hour_Ahead_Forecast"
        ]
    ).copy()

    cumulative_2hr_df = cumulative_2hr_df[
        (cumulative_2hr_df["hour"] >= 6.5)
        & (cumulative_2hr_df["hour"] <= 17.5)
        & (cumulative_2hr_df["Actual_GHI"] > 50)
    ].copy()

    if not cumulative_2hr_df.empty:

        cumulative_2hr_start = (
            cumulative_2hr_df["valid_time_ist"]
            .dt.date
            .min()
        )

        cumulative_2hr_end = (
            cumulative_2hr_df["valid_time_ist"]
            .dt.date
            .max()
        )

        st.markdown(
            f"### 📊 Cumulative Performance of 2-Hour Ahead Forecast "
            f"({cumulative_2hr_start} to {cumulative_2hr_end})"
        )

        actual_cum_2hr = cumulative_2hr_df["Actual_GHI"]
        gfs_cum_2hr = cumulative_2hr_df["GFS_GHI"]
        daily_cum_2hr = cumulative_2hr_df[
            "Daily_Forecast_GHI"
        ]
        forecast_cum_2hr = cumulative_2hr_df[
            "Two_Hour_Ahead_Forecast"
        ]

        # =====================================================
        # MAPE
        # =====================================================

        cumulative_mape_gfs = (
            (
                (actual_cum_2hr - gfs_cum_2hr).abs()
                / actual_cum_2hr
            ).mean()
            * 100
        )

        cumulative_mape_daily = (
            (
                (actual_cum_2hr - daily_cum_2hr).abs()
                / actual_cum_2hr
            ).mean()
            * 100
        )

        cumulative_mape_2hr = (
            (
                (actual_cum_2hr - forecast_cum_2hr).abs()
                / actual_cum_2hr
            ).mean()
            * 100
        )

        # =====================================================
        # MAE
        # =====================================================

        cumulative_mae_gfs = (
            actual_cum_2hr - gfs_cum_2hr
        ).abs().mean()

        cumulative_mae_daily = (
            actual_cum_2hr - daily_cum_2hr
        ).abs().mean()

        cumulative_mae_2hr = (
            actual_cum_2hr - forecast_cum_2hr
        ).abs().mean()

        # =====================================================
        # RMSE
        # =====================================================

        cumulative_rmse_gfs = np.sqrt(
            ((actual_cum_2hr - gfs_cum_2hr) ** 2).mean()
        )

        cumulative_rmse_daily = np.sqrt(
            ((actual_cum_2hr - daily_cum_2hr) ** 2).mean()
        )

        cumulative_rmse_2hr = np.sqrt(
            ((actual_cum_2hr - forecast_cum_2hr) ** 2).mean()
        )

        comparison_labels = [
            "Raw GFS Prediction",
            "After Daily Forecast",
            "After 2 Hour Ahead"
        ]

        comparison_colors = [
            GFS_COLOR,
            DAILY_FORECAST_COLOR,
            TWO_HOUR_COLOR
        ]

        twohr_metric_col1, twohr_metric_col2, twohr_metric_col3 = (
            st.columns(3)
        )

        # =====================================================
        # CUMULATIVE 2-HOUR MAPE
        # =====================================================

        with twohr_metric_col1:
            with st.container(border=True):

                fig_2hr_mape = go.Figure()

                fig_2hr_mape.add_trace(go.Bar(
                    x=comparison_labels,
                    y=[
                        cumulative_mape_gfs,
                        cumulative_mape_daily,
                        cumulative_mape_2hr
                    ],
                    text=[
                        f"{cumulative_mape_gfs:.2f}",
                        f"{cumulative_mape_daily:.2f}",
                        f"{cumulative_mape_2hr:.2f}"
                    ],
                    textposition="auto",
                    marker_color=comparison_colors
                ))

                fig_2hr_mape.update_layout(
                    title="MAPE",
                    xaxis_title="Forecast Stage",
                    yaxis_title="MAPE (%)",
                    height=350,
                    margin=dict(
                        l=35,
                        r=20,
                        t=55,
                        b=40
                    ),
                    showlegend=False
                )

                st.plotly_chart(
                    fig_2hr_mape,
                    use_container_width=True,
                    key="cumulative_2hr_mape_chart"
                )

        # =====================================================
        # CUMULATIVE 2-HOUR MAE
        # =====================================================

        with twohr_metric_col2:
            with st.container(border=True):

                fig_2hr_mae = go.Figure()

                fig_2hr_mae.add_trace(go.Bar(
                    x=comparison_labels,
                    y=[
                        cumulative_mae_gfs,
                        cumulative_mae_daily,
                        cumulative_mae_2hr
                    ],
                    text=[
                        f"{cumulative_mae_gfs:.2f}",
                        f"{cumulative_mae_daily:.2f}",
                        f"{cumulative_mae_2hr:.2f}"
                    ],
                    textposition="auto",
                    marker_color=comparison_colors
                ))

                fig_2hr_mae.update_layout(
                    title="MAE",
                    xaxis_title="Forecast Stage",
                    yaxis_title="MAE",
                    height=350,
                    margin=dict(
                        l=35,
                        r=20,
                        t=55,
                        b=40
                    ),
                    showlegend=False
                )

                st.plotly_chart(
                    fig_2hr_mae,
                    use_container_width=True,
                    key="cumulative_2hr_mae_chart"
                )

        # =====================================================
        # CUMULATIVE 2-HOUR RMSE
        # =====================================================

        with twohr_metric_col3:
            with st.container(border=True):

                fig_2hr_rmse = go.Figure()

                fig_2hr_rmse.add_trace(go.Bar(
                    x=comparison_labels,
                    y=[
                        cumulative_rmse_gfs,
                        cumulative_rmse_daily,
                        cumulative_rmse_2hr
                    ],
                    text=[
                        f"{cumulative_rmse_gfs:.2f}",
                        f"{cumulative_rmse_daily:.2f}",
                        f"{cumulative_rmse_2hr:.2f}"
                    ],
                    textposition="auto",
                    marker_color=comparison_colors
                ))

                fig_2hr_rmse.update_layout(
                    title="RMSE",
                    xaxis_title="Forecast Stage",
                    yaxis_title="RMSE",
                    height=350,
                    margin=dict(
                        l=35,
                        r=20,
                        t=55,
                        b=40
                    ),
                    showlegend=False
                )

                st.plotly_chart(
                    fig_2hr_rmse,
                    use_container_width=True,
                    key="cumulative_2hr_rmse_chart"
                )

    else:
        st.markdown(
            f"### 📊 Cumulative Performance of 2-Hour Ahead Forecast "
            f"(Through {previous_day})"
        )

        st.warning(
            "No valid 2-hour-ahead forecast data is available "
            "from the beginning of the dataset through the previous day."
        )

    # =====================================================
    # OVERALL FULL-DATA PERFORMANCE METRICS
    # =====================================================

    overall_df = df.dropna(
        subset=[
            "Actual_GHI",
            "GFS_GHI",
            "Daily_Forecast_GHI"
        ]
    ).copy()

    overall_df["hour"] = (
        overall_df["valid_time_ist"].dt.hour
        + overall_df["valid_time_ist"].dt.minute / 60
    )

    overall_df = overall_df[
        (overall_df["hour"] >= 6.5)
        & (overall_df["hour"] <= 17.5)
        & (overall_df["Actual_GHI"] > 50)
    ].copy()

    # =====================================================
    # METRIC CARD FUNCTION
    # =====================================================

    def show_metric_card(title, metric_rows):
        """
        metric_rows:
        [
            (label, displayed_value, value_color, font_size),
            ...
        ]
        """

        with st.container(border=True):

            st.markdown(
                f"""
                <h3 style="
                    color:#FF3B30;
                    font-size:1.45rem;
                    margin-top:0;
                    margin-bottom:14px;
                ">
                    {title}
                </h3>
                """,
                unsafe_allow_html=True
            )

            for row_number, row in enumerate(metric_rows):

                label = row[0]
                displayed_value = row[1]
                value_color = row[2]
                font_size = row[3]

                metric_html = (
                    f'<div style="'
                    f'padding-top:12px;'
                    f'padding-bottom:12px;">'

                    f'<div style="'
                    f'font-size:0.88rem;'
                    f'font-weight:600;'
                    f'margin-bottom:5px;'
                    f'color:inherit;">'
                    f'{label}'
                    f'</div>'

                    f'<div style="'
                    f'color:{value_color};'
                    f'font-size:{font_size};'
                    f'font-weight:750;'
                    f'line-height:1.15;">'
                    f'{displayed_value}'
                    f'</div>'

                    f'</div>'
                )

                st.markdown(
                    metric_html,
                    unsafe_allow_html=True
                )

    if not overall_df.empty:

        # =====================================================
        # DAILY FORECAST METRICS
        # =====================================================

        daily_start_date = (
            overall_df["valid_time_ist"].dt.date.min()
        )

        daily_end_date = (
            overall_df["valid_time_ist"].dt.date.max()
        )

        actual_all = overall_df["Actual_GHI"]
        gfs_all = overall_df["GFS_GHI"]
        daily_all = overall_df["Daily_Forecast_GHI"]

        overall_mape_before = (
            ((actual_all - gfs_all).abs() / actual_all).mean()
            * 100
        )

        overall_mape_after = (
            ((actual_all - daily_all).abs() / actual_all).mean()
            * 100
        )

        overall_mae_before = (
            (actual_all - gfs_all).abs().mean()
        )

        overall_mae_after = (
            (actual_all - daily_all).abs().mean()
        )

        overall_rmse_before = np.sqrt(
            ((actual_all - gfs_all) ** 2).mean()
        )

        overall_rmse_after = np.sqrt(
            ((actual_all - daily_all) ** 2).mean()
        )

        st.markdown("## 📑 Overall Forecast Performance")

        left_summary, right_summary = st.columns(2)

        # =====================================================
        # LEFT SIDE: DAILY FORECAST
        # =====================================================

        with left_summary:

            with st.container(border=True):

                st.markdown(
                    f"""
                    <div style="
                        font-size:1.5rem;
                        font-weight:700;
                        line-height:1.25;
                        white-space:nowrap;
                        margin-bottom:8px;
                    ">
                        📈 Daily Forecast
                        ({daily_start_date} to {daily_end_date})
                    </div>
                    """,
                    unsafe_allow_html=True
                )

                st.markdown(
                    """
                    <div style="
                        font-size:0.92rem;
                        color:inherit;
                        margin-bottom:2px;
                    ">
                        Comparison of Actual GHI, GFS and Daily Forecast GHI
                    </div>
                    """,
                    unsafe_allow_html=True
                )

            k1, k2, k3 = st.columns(3)

            # ---------------- MAPE ----------------
            with k1:
                show_metric_card(
                    "🎯 MAPE",
                    [
                        (
                            "Actual vs GFS",
                            f"{overall_mape_before:.2f}%",
                            GFS_COLOR,
                            "1.40rem"
                        ),
                        (
                            "Actual vs Daily Forecast",
                            f"{overall_mape_after:.2f}%",
                            DAILY_FORECAST_COLOR,
                            "2.15rem"
                        )
                    ]
                )

            # ---------------- MAE ----------------
            with k2:
                show_metric_card(
                    "📊 MAE",
                    [
                        (
                            "Actual vs GFS",
                            f"{overall_mae_before:.2f}",
                            GFS_COLOR,
                            "1.40rem"
                        ),
                        (
                            "Actual vs Daily Forecast",
                            f"{overall_mae_after:.2f}",
                            DAILY_FORECAST_COLOR,
                            "2.15rem"
                        )
                    ]
                )

            # ---------------- RMSE ----------------
            with k3:
                show_metric_card(
                    "〽️ RMSE",
                    [
                        (
                            "Actual vs GFS",
                            f"{overall_rmse_before:.2f}",
                            GFS_COLOR,
                            "1.40rem"
                        ),
                        (
                            "Actual vs Daily Forecast",
                            f"{overall_rmse_after:.2f}",
                            DAILY_FORECAST_COLOR,
                            "2.15rem"
                        )
                    ]
                )

        # =====================================================
        # RIGHT SIDE: 2-HOUR-AHEAD FORECAST
        # =====================================================

        with right_summary:

            two_hour_metrics_df = overall_df.dropna(
                subset=["Two_Hour_Ahead_Forecast"]
            ).copy()

            if not two_hour_metrics_df.empty:

                twohr_start_date = (
                    two_hour_metrics_df[
                        "valid_time_ist"
                    ].dt.date.min()
                )

                twohr_end_date = (
                    two_hour_metrics_df[
                        "valid_time_ist"
                    ].dt.date.max()
                )

                actual_2hr = (
                    two_hour_metrics_df["Actual_GHI"]
                )

                gfs_2hr = (
                    two_hour_metrics_df["GFS_GHI"]
                )

                daily_2hr = (
                    two_hour_metrics_df["Daily_Forecast_GHI"]
                )

                forecast_2hr = (
                    two_hour_metrics_df[
                        "Two_Hour_Ahead_Forecast"
                    ]
                )

                # =====================================================
                # MAPE
                # =====================================================

                mape_gfs = (
                    (
                        (actual_2hr - gfs_2hr).abs()
                        / actual_2hr
                    ).mean()
                    * 100
                )

                mape_daily = (
                    (
                        (actual_2hr - daily_2hr).abs()
                        / actual_2hr
                    ).mean()
                    * 100
                )

                mape_2hr = (
                    (
                        (actual_2hr - forecast_2hr).abs()
                        / actual_2hr
                    ).mean()
                    * 100
                )

                # =====================================================
                # MAE
                # =====================================================

                mae_gfs = (
                    (actual_2hr - gfs_2hr).abs().mean()
                )

                mae_daily = (
                    (actual_2hr - daily_2hr).abs().mean()
                )

                mae_2hr = (
                    (actual_2hr - forecast_2hr).abs().mean()
                )

                # =====================================================
                # RMSE
                # =====================================================

                rmse_gfs = np.sqrt(
                    ((actual_2hr - gfs_2hr) ** 2).mean()
                )

                rmse_daily = np.sqrt(
                    ((actual_2hr - daily_2hr) ** 2).mean()
                )

                rmse_2hr = np.sqrt(
                    ((actual_2hr - forecast_2hr) ** 2).mean()
                )

                with st.container(border=True):

                    st.markdown(
                        f"""
                        <div style="
                            font-size:1.5rem;
                            font-weight:700;
                            line-height:1.25;
                            white-space:nowrap;
                            margin-bottom:8px;
                        ">
                            🕒 2-Hour Ahead Forecast
                            ({twohr_start_date} to {twohr_end_date})
                        </div>
                        """,
                        unsafe_allow_html=True
                    )

                    st.markdown(
                        """
                        <div style="
                            font-size:0.92rem;
                            color:inherit;
                            margin-bottom:2px;
                        ">
                            Calculated only for rows where
                            2-Hour Ahead Forecast is available
                        </div>
                        """,
                        unsafe_allow_html=True
                    )

                h1, h2, h3 = st.columns(3)

                # ---------------- MAPE ----------------
                with h1:
                    show_metric_card(
                        "🎯 MAPE",
                        [
                            (
                                "Actual vs GFS",
                                f"{mape_gfs:.2f}%",
                                GFS_COLOR,
                                "1.40rem"
                            ),
                            (
                                "Actual vs 2-Hour Ahead",
                                f"{mape_2hr:.2f}%",
                                TWO_HOUR_COLOR,
                                "2.15rem"
                            )
                        ]
                    )

                # ---------------- MAE ----------------
                with h2:
                    show_metric_card(
                        "📊 MAE",
                        [
                            (
                                "Actual vs GFS",
                                f"{mae_gfs:.2f}",
                                GFS_COLOR,
                                "1.40rem"
                            ),
                            (
                                "Actual vs 2-Hour Ahead",
                                f"{mae_2hr:.2f}",
                                TWO_HOUR_COLOR,
                                "2.15rem"
                            )
                        ]
                    )

                # ---------------- RMSE ----------------
                with h3:
                    show_metric_card(
                        "〽️ RMSE",
                        [
                            (
                                "Actual vs GFS",
                                f"{rmse_gfs:.2f}",
                                GFS_COLOR,
                                "1.40rem"
                            ),
                            (
                                "Actual vs 2-Hour Ahead",
                                f"{rmse_2hr:.2f}",
                                TWO_HOUR_COLOR,
                                "2.15rem"
                            )
                        ]
                    )

            else:
                with st.container(border=True):
                    st.markdown(
                        "### 🕒 2-Hour Ahead Forecast"
                    )

                    st.warning(
                        "No valid 2-hour-ahead forecast data is "
                        "available for overall performance."
                    )

    else:
        st.warning(
            "Not enough valid data to calculate "
            "overall forecast performance."
        )

# =====================================================
# MONTH-WISE OVERALL MAE — 2-HOUR AHEAD FORECAST
# =====================================================

monthly_2hr_performance, twohr_monthly_start, twohr_monthly_end = (
    calculate_monthly_2hr_mae(df)
)

if not monthly_2hr_performance.empty:

    st.markdown(
        f"## 📊 Month-Wise MAE of 2-Hour Ahead Forecast "
        f"({twohr_monthly_start} to {twohr_monthly_end})"
    )

    with st.container(border=True):

        fig_monthly_2hr = go.Figure()

        fig_monthly_2hr.add_trace(go.Bar(
            x=monthly_2hr_performance["Month"],
            y=monthly_2hr_performance["Monthly_MAE"],
            name="2-Hour Ahead Forecast MAE",
            marker=dict(
                color=TWO_HOUR_COLOR,
                line=dict(
                    color="#1F7A1F",
                    width=1.2
                )
            ),
            text=[
                f"{value:.2f}"
                for value in monthly_2hr_performance["Monthly_MAE"]
            ],
            textposition="outside",
            cliponaxis=False,
            hovertemplate=(
                "<b>%{x}</b><br>"
                "MAE: %{y:.2f}"
                "<extra></extra>"
            )
        ))

        maximum_2hr_mae = (
            monthly_2hr_performance["Monthly_MAE"].max()
        )

        twohr_ymax = (
            maximum_2hr_mae * 1.18
            if pd.notna(maximum_2hr_mae) and maximum_2hr_mae > 0
            else 100
        )

        fig_monthly_2hr.update_layout(
            xaxis_title="Month",
            yaxis_title="MAE",
            height=500,
            bargap=0.25,
            showlegend=False,
            margin=dict(
                l=45,
                r=25,
                t=30,
                b=55
            )
        )

        fig_monthly_2hr.update_xaxes(
            type="category",
            categoryorder="array",
            categoryarray=[
                "Jan", "Feb", "Mar", "Apr",
                "May", "Jun", "Jul", "Aug",
                "Sep", "Oct", "Nov", "Dec"
            ],
            fixedrange=True
        )

        fig_monthly_2hr.update_yaxes(
            range=[0, twohr_ymax],
            rangemode="tozero",
            fixedrange=True
        )

        st.plotly_chart(
            fig_monthly_2hr,
            width="stretch",
            key="monthwise_2hour_forecast_mae",
            config={
                "displayModeBar": False,
                "staticPlot": True,
                "responsive": True
            }
        )

else:
    st.warning(
        "Not enough valid 2-hour-ahead forecast data is available "
        "to calculate month-wise MAE."
    )

# =====================================================
# TIME-SLOT-WISE MAE — 2-HOUR AHEAD FORECAST
# One bar per timestamp across all available days
# =====================================================

@st.cache_data
def calculate_timeslot_2hr_mae(input_df):

    timeslot_df = input_df.dropna(
        subset=[
            "valid_time_ist",
            "Actual_GHI",
            "Two_Hour_Ahead_Forecast"
        ]
    ).copy()

    timeslot_df["hour"] = (
        timeslot_df["valid_time_ist"].dt.hour
        + timeslot_df["valid_time_ist"].dt.minute / 60
    )

    # Apply the same evaluation rule used in other metrics
    timeslot_df = timeslot_df[
        (timeslot_df["hour"] >= 6.5)
        & (timeslot_df["hour"] <= 17.5)
        & (timeslot_df["Actual_GHI"] > 50)
    ].copy()

    if timeslot_df.empty:
        return pd.DataFrame(), None, None

    # Absolute error for each individual prediction
    timeslot_df["Absolute_Error"] = (
        timeslot_df["Actual_GHI"]
        - timeslot_df["Two_Hour_Ahead_Forecast"]
    ).abs()

    # Time labels in 24-hour format
    timeslot_df["Time_Slot"] = (
        timeslot_df["valid_time_ist"].dt.strftime("%H:%M")
    )

    # Numeric time used only for correct chronological sorting
    timeslot_df["Time_Order"] = (
        timeslot_df["valid_time_ist"].dt.hour * 60
        + timeslot_df["valid_time_ist"].dt.minute
    )

    timeslot_performance = (
        timeslot_df
        .groupby(
            ["Time_Order", "Time_Slot"],
            as_index=False
        )
        .agg(
            Time_Slot_MAE=("Absolute_Error", "mean"),
            Prediction_Count=("Absolute_Error", "size")
        )
        .sort_values("Time_Order")
        .reset_index(drop=True)
    )

    start_date = (
        timeslot_df["valid_time_ist"].dt.date.min()
    )

    end_date = (
        timeslot_df["valid_time_ist"].dt.date.max()
    )

    return timeslot_performance, start_date, end_date


# =====================================================
# CALCULATE TIME-SLOT-WISE MAE
# =====================================================

(
    timeslot_2hr_performance,
    timeslot_2hr_start,
    timeslot_2hr_end
) = calculate_timeslot_2hr_mae(df)


if not timeslot_2hr_performance.empty:

    st.markdown(
        f"## ⏱️ Time-Slot-Wise MAE of 2-Hour Ahead Forecast "
        f"({timeslot_2hr_start} to {timeslot_2hr_end})"
    )

    with st.container(border=True):

        fig_timeslot_2hr_mae = go.Figure()

        fig_timeslot_2hr_mae.add_trace(go.Bar(
            x=timeslot_2hr_performance["Time_Slot"],
            y=timeslot_2hr_performance["Time_Slot_MAE"],
            name="2-Hour Ahead MAE",

            marker=dict(
                color=TWO_HOUR_COLOR,
                line=dict(
                    color="#1F7A1F",
                    width=1.2
                )
            ),

            text=[
                f"{value:.2f}"
                for value in timeslot_2hr_performance[
                    "Time_Slot_MAE"
                ]
            ],

            textposition="outside",
            cliponaxis=False,

            customdata=timeslot_2hr_performance[
                "Prediction_Count"
            ],

            hovertemplate=(
                "<b>Time: %{x}</b><br>"
                "MAE: %{y:.2f}<br>"
                "Predictions: %{customdata}"
                "<extra></extra>"
            )
        ))

        maximum_timeslot_mae = (
            timeslot_2hr_performance[
                "Time_Slot_MAE"
            ].max()
        )

        timeslot_ymax = (
            maximum_timeslot_mae * 1.18
            if (
                pd.notna(maximum_timeslot_mae)
                and maximum_timeslot_mae > 0
            )
            else 100
        )

        ordered_time_slots = (
            timeslot_2hr_performance[
                "Time_Slot"
            ].tolist()
        )

        fig_timeslot_2hr_mae.update_layout(
            xaxis_title="Time",
            yaxis_title="MAE",
            height=500,
            bargap=0.22,
            showlegend=False,
            margin=dict(
                l=45,
                r=25,
                t=35,
                b=60
            )
        )

        fig_timeslot_2hr_mae.update_xaxes(
            type="category",
            categoryorder="array",
            categoryarray=ordered_time_slots,
            tickmode="array",
            tickvals=ordered_time_slots,
            ticktext=ordered_time_slots,
            tickangle=0,
            fixedrange=True
        )

        fig_timeslot_2hr_mae.update_yaxes(
            range=[0, timeslot_ymax],
            rangemode="tozero",
            fixedrange=True
        )

        st.plotly_chart(
            fig_timeslot_2hr_mae,
            width="stretch",
            key="timeslot_2hr_mae_chart",
            config={
                "displayModeBar": False,
                "staticPlot": True,
                "responsive": True
            }
        )

else:
    st.warning(
        "Not enough valid 2-hour-ahead forecast data is available "
        "to calculate time-slot-wise MAE."
    )

# =====================================================
# TIME-SLOT-WISE MAPE — 2-HOUR AHEAD FORECAST
# Each bar represents the average MAPE at that time
# across all available days
# =====================================================

@st.cache_data
def calculate_timeslot_2hr_mape(input_df):

    timeslot_mape_df = input_df.dropna(
        subset=[
            "valid_time_ist",
            "Actual_GHI",
            "Two_Hour_Ahead_Forecast"
        ]
    ).copy()

    timeslot_mape_df["hour"] = (
        timeslot_mape_df["valid_time_ist"].dt.hour
        + timeslot_mape_df["valid_time_ist"].dt.minute / 60
    )

    # Same evaluation conditions used in the dashboard
    timeslot_mape_df = timeslot_mape_df[
        (timeslot_mape_df["hour"] >= 6.5)
        & (timeslot_mape_df["hour"] <= 17.5)
        & (timeslot_mape_df["Actual_GHI"] > 50)
    ].copy()

    if timeslot_mape_df.empty:
        return pd.DataFrame(), None, None

    # Absolute percentage error for each prediction
    timeslot_mape_df["APE"] = (
        (
            timeslot_mape_df["Actual_GHI"]
            - timeslot_mape_df["Two_Hour_Ahead_Forecast"]
        ).abs()
        / timeslot_mape_df["Actual_GHI"]
    ) * 100

    # Display time in 24-hour format
    timeslot_mape_df["Time_Slot"] = (
        timeslot_mape_df["valid_time_ist"].dt.strftime("%H:%M")
    )

    # Numeric value used to sort times correctly
    timeslot_mape_df["Time_Order"] = (
        timeslot_mape_df["valid_time_ist"].dt.hour * 60
        + timeslot_mape_df["valid_time_ist"].dt.minute
    )

    timeslot_mape_performance = (
        timeslot_mape_df
        .groupby(
            ["Time_Order", "Time_Slot"],
            as_index=False
        )
        .agg(
            Time_Slot_MAPE=("APE", "mean"),
            Prediction_Count=("APE", "size")
        )
        .sort_values("Time_Order")
        .reset_index(drop=True)
    )

    start_date = (
        timeslot_mape_df["valid_time_ist"].dt.date.min()
    )

    end_date = (
        timeslot_mape_df["valid_time_ist"].dt.date.max()
    )

    return (
        timeslot_mape_performance,
        start_date,
        end_date
    )


# =====================================================
# CALCULATE TIME-SLOT-WISE MAPE
# =====================================================

(
    timeslot_2hr_mape_performance,
    timeslot_2hr_mape_start,
    timeslot_2hr_mape_end
) = calculate_timeslot_2hr_mape(df)


if not timeslot_2hr_mape_performance.empty:

    st.markdown(
        f"## ⏱️ Time-Slot-Wise MAPE of 2-Hour Ahead Forecast "
        f"({timeslot_2hr_mape_start} to {timeslot_2hr_mape_end})"
    )

    with st.container(border=True):

        fig_timeslot_2hr_mape = go.Figure()

        fig_timeslot_2hr_mape.add_trace(
            go.Bar(
                x=timeslot_2hr_mape_performance["Time_Slot"],
                y=timeslot_2hr_mape_performance[
                    "Time_Slot_MAPE"
                ],

                marker=dict(
                    color=TWO_HOUR_COLOR,
                    line=dict(
                        color="#1F7A1F",
                        width=1.2
                    )
                ),

                text=[
                    f"{value:.2f}%"
                    for value in timeslot_2hr_mape_performance[
                        "Time_Slot_MAPE"
                    ]
                ],

                textposition="outside",
                cliponaxis=False,

                customdata=timeslot_2hr_mape_performance[
                    "Prediction_Count"
                ],

                hovertemplate=(
                    "<b>Time: %{x}</b><br>"
                    "MAPE: %{y:.2f}%<br>"
                    "Number of predictions: %{customdata}"
                    "<extra></extra>"
                ),

                showlegend=False
            )
        )

        maximum_timeslot_mape = (
            timeslot_2hr_mape_performance[
                "Time_Slot_MAPE"
            ].max()
        )

        timeslot_mape_ymax = (
            maximum_timeslot_mape * 1.18
            if (
                pd.notna(maximum_timeslot_mape)
                and maximum_timeslot_mape > 0
            )
            else 10
        )

        ordered_time_slots = (
            timeslot_2hr_mape_performance[
                "Time_Slot"
            ].tolist()
        )

        fig_timeslot_2hr_mape.update_layout(
            xaxis_title="Time",
            yaxis_title="MAPE (%)",
            height=500,
            bargap=0.22,
            showlegend=False,
            margin=dict(
                l=45,
                r=25,
                t=35,
                b=60
            )
        )

        fig_timeslot_2hr_mape.update_xaxes(
            type="category",
            categoryorder="array",
            categoryarray=ordered_time_slots,
            tickmode="array",
            tickvals=ordered_time_slots,
            ticktext=ordered_time_slots,
            tickangle=0,
            fixedrange=True
        )

        fig_timeslot_2hr_mape.update_yaxes(
            range=[0, timeslot_mape_ymax],
            rangemode="tozero",
            fixedrange=True
        )

        st.plotly_chart(
            fig_timeslot_2hr_mape,
            width="stretch",
            key="timeslot_2hr_mape_chart",
            config={
                "displayModeBar": False,
                "staticPlot": True,
                "responsive": True
            }
        )

else:
    st.warning(
        "Not enough valid 2-hour-ahead forecast data is available "
        "to calculate time-slot-wise MAPE."
    )


# =====================================================
# INDIVIDUAL MAPE DISTRIBUTION — 2-HOUR AHEAD FORECAST
# Each valid timestamp is counted separately
# =====================================================

@st.cache_data
def calculate_individual_2hr_mape_distribution(input_df):

    distribution_df = input_df.dropna(
        subset=[
            "valid_time_ist",
            "Actual_GHI",
            "Two_Hour_Ahead_Forecast"
        ]
    ).copy()

    distribution_df["hour"] = (
        distribution_df["valid_time_ist"].dt.hour
        + distribution_df["valid_time_ist"].dt.minute / 60
    )

    # Same evaluation conditions used in the dashboard
    distribution_df = distribution_df[
        (distribution_df["hour"] >= 6.5)
        & (distribution_df["hour"] <= 17.5)
        & (distribution_df["Actual_GHI"] > 50)
    ].copy()

    if distribution_df.empty:
        return pd.DataFrame(), None, None, 0

    # Percentage error for every individual timestamp
    distribution_df["Individual_MAPE"] = (
        (
            distribution_df["Actual_GHI"]
            - distribution_df["Two_Hour_Ahead_Forecast"]
        ).abs()
        / distribution_df["Actual_GHI"]
    ) * 100

    start_date = (
        distribution_df["valid_time_ist"].dt.date.min()
    )

    end_date = (
        distribution_df["valid_time_ist"].dt.date.max()
    )

    # Classify every timestamp separately
    distribution_df["MAPE_Range"] = pd.cut(
        distribution_df["Individual_MAPE"],
        bins=[
            0,
            5,
            10,
            15,
            20,
            np.inf
        ],
        labels=[
            "0–5%",
            ">5–10%",
            ">10–15%",
            ">15–20%",
            ">20%"
        ],
        include_lowest=True,
        right=True
    )

    category_order = [
        "0–5%",
        ">5–10%",
        ">10–15%",
        ">15–20%",
        ">20%"
    ]

    distribution_counts = (
        distribution_df["MAPE_Range"]
        .value_counts()
        .reindex(category_order, fill_value=0)
        .rename_axis("MAPE Range")
        .reset_index(name="Number of Predictions")
    )

    total_predictions = len(distribution_df)

    return (
        distribution_counts,
        start_date,
        end_date,
        total_predictions
    )


# =====================================================
# CALCULATE INDIVIDUAL DISTRIBUTION
# =====================================================

(
    individual_mape_distribution_df,
    individual_distribution_start,
    individual_distribution_end,
    total_individual_predictions
) = calculate_individual_2hr_mape_distribution(df)


if not individual_mape_distribution_df.empty:

    st.markdown(
        f"## 🎯 MAPE Distribution of 2-Hour Ahead Forecast "
        f"({individual_distribution_start} to "
        f"{individual_distribution_end})"
    )

    with st.container(border=True):

        # Colours kept separate from the forecast-series colours
        distribution_colors = [
            "#5E35B1",  # Deep purple
            "#8E67C7",  # Light purple
            "#EC407A",  # Pink
            "#AB47BC",  # Violet
            "#78909C"   # Slate grey
        ]

        fig_individual_mape_distribution = go.Figure()

        fig_individual_mape_distribution.add_trace(
            go.Pie(
                labels=individual_mape_distribution_df[
                    "MAPE Range"
                ],
                values=individual_mape_distribution_df[
                    "Number of Predictions"
                ],

                hole=0.44,

                marker=dict(
                    colors=distribution_colors,
                    line=dict(
                        color="white",
                        width=2.5
                    )
                ),

                texttemplate=(
                    "<b>%{label}</b><br>"
                    "%{value} predictions<br>"
                    "%{percent:.1%}"
                ),

                textposition="auto",

                insidetextfont=dict(
                    size=14,
                    color="white"
                ),

                hovertemplate=(
                    "<b>%{label}</b><br>"
                    "Predictions: %{value}<br>"
                    "Share: %{percent:.2%}"
                    "<extra></extra>"
                ),

                sort=False,
                direction="clockwise",
                pull=[0.035, 0, 0, 0, 0],
                automargin=True
            )
        )

        # Total number of individual predictions in the centre
        fig_individual_mape_distribution.update_layout(
            height=580,
            showlegend=False,

            annotations=[
                dict(
                    text=(
                        f"<b>{total_individual_predictions}</b><br>"
                        "<span style='font-size:13px;'>"
                        "Predictions"
                        "</span>"
                    ),
                    x=0.5,
                    y=0.5,
                    showarrow=False,
                    align="center",
                    font=dict(size=24)
                )
            ],

            margin=dict(
                l=65,
                r=65,
                t=40,
                b=65
            ),

            uniformtext=dict(
                minsize=10,
                mode="hide"
            )
        )

        st.plotly_chart(
            fig_individual_mape_distribution,
            width="stretch",
            key="individual_2hr_mape_distribution",
            config={
                "displayModeBar": False,
                "staticPlot": True,
                "responsive": True
            }
        )

else:
    st.warning(
        "Not enough valid 2-hour-ahead forecast data is "
        "available to calculate the individual MAPE distribution."
    )
